#include "myUtil.h"

#include <iostream>


// Declare the external function generated by Flex
extern int yylex();

int main() {
    std::cout << sopa() << " Lexical analyzer activated:" << std::endl;

    // Execute the lexer
    yylex();

    std::cout << "\nLexical analysis complete." << std::endl;
    return 0;
}